keys:
  tavily_api_key: "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"
  langsmith_api_key: "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"
  pinecone_key : "pcsk_3zcfcV_PzG8zuw5dMeaffb2m8hV19MipxLmykB7yXwjZUD5CJQXt2Pfnqdpnpgtr6z7msA"
  mistral_api_key : "sciygleTGG44h8hqKV0Q1iUYxuQR3mlM"